define([], function() {
  return {
      "PropertyPaneDescription": "Use the settings panel to configure the webpart",
      "BasicGroupName": "OnThisPage Web Part Settings",
      "PropertyPaneDescription2": "Use the settings panel to configure the branding",
      "BasicGroupName2": "Branding Settings",
      "showOTPHeading": "Show title",
      "headingText": "Title",
      "levelsToShow": "Number of Heading levels to show",
      "oneLevelText": "Show 'Heading 1' Only",
      "twoLevelsText": "Show 'Heading 1 and 2'",
      "headingTextDefaultValue": "On This Page",
      "showBackToTop": "Show back to top in paragraph",
      "backToTopText": "Label 'Back to top'",
      "backToTopDefaultValue": "Back to top",
      "backToTopFieldDescription": "Text in this field will be added to the text web part underneath each paragraph.",
      "showBackToPreviousPage": "Show back to previous page",
      "backToPreviousText": "Label 'Back to previous page'",
      "backToPreviousDefaultValue": "Back to previous page",
      "backToPreviousFieldDescription": "",
      "pageInEditMode": "Page is in edit mode.",
      "iconDescription": "Office UI Fabric icon name",
      "iconGroup": "Icons",
      "iconOTPItem": "Icon for 'Heading 1'",
      "iconOTPItem2": "Icon for 'Heading 2'",
      "iconPreviousPage": "Icon for 'Previous page'",
      "sampleItemLabel": "Sample item",
      "errorFieldCannotBeEmpty": "This field cannot be empty. Fill in a value!",
      "errorToggleFieldEmpty": "This field cannot be empty, if you do no want to use this field, toggle it off!",
      "fixOTP": "Fix the menu",
      "otpBackgroundColorDescription":"Add a background color in the format #ffffff or Transparent",
      "otpBackgroundColor":"Background Color",
      "otpFontcolor": "Font Color",
      "otpFontColorDescription": "Add a contrasting color to the background color"
  }
});
